apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{MY_NAME}}
  namespace: {{MY_NS}}
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["198.51.100.0/12"]
    pods:
      cidrBlocks: ["192.0.2.0/16"]
    serviceDomain: "cluster.local"
  topology:
    class: tanzukubernetescluster
    version: v1.25.7---vmware.3-fips.1-tkg.1 
    controlPlane:
      replicas: 3
    workers:
      # node pools
      machineDeployments:
        - class: node-pool
          name: np1-worker
          replicas: 75
        - class: node-pool
          name: np2-worker
          replicas: 75
    variables:
      - name: vmClass
        value: best-effort-xsmall
      - name: storageClass
        value: vmc-workload-storage-policy-cluster-1
