apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: cp1w1
  namespace: wcpns5
spec:
  topology:
    controlPlane:
      tkr:
        reference:
          name: v1.21.6---vmware.1-tkg.1.b3d708a-xcf6c
      replicas: 1
      vmClass: best-effort-medium
      storageClass: nfs-policy
    nodePools:
    - replicas: 1
      name: np-1
      vmClass: best-effort-xsmall
      storageClass: nfs-policy
  settings:
    network:
      cni:
        name: calico
      services:
        cidrBlocks:
        - 198.51.100.0/12
      pods:
        cidrBlocks:
        - 192.0.2.0/16
      serviceDomain: cluster.local
