apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: {{MY_NAME}}
  namespace: {{MY_NS}}
spec:
  topology:
    controlPlane:
      count: 1
      class: best-effort-large
      storageClass: 'vmc-workload-storage-policy-cluster-1'
    workers:
      count: 4
      class: best-effort-xsmall
      storageClass: 'vmc-workload-storage-policy-cluster-1'
  distribution:
    version: v1.20.2+vmware.1-tkg.1.1d4f79a
  settings:
    network:
      cni:
        name: antrea
      services:
        cidrBlocks: ["198.51.100.0/12"]
      pods:
        cidrBlocks: ["192.0.2.0/16"]
