apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{pvc_name}}
  namespace: {{ns}}
  annotations:
    volume.beta.kubernetes.io/storage-class: vmc-workload-storage-policy-cluster-1
  labels:
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: vmc-workload-storage-policy-cluster-1
